### PR TITLE
create attraction.html, attraction.css, attraction.js

### PR DESCRIPTION
**Pull request by esperanzacheng**
彭彭好，我是鄭晴云(Discord: Erin Cheng)
http://54.87.33.165:3000/
http://54.87.33.165:3000/attraction/1

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your viewport meta tag is incorrect.

**Comment by esperanzacheng** [comment]
fix the viewport meta tag error ><

**Review by cwpeng — CHANGES_REQUESTED** [review]
Keyvisual image in home page in 1920px shown below:

**Comment by esperanzacheng** [comment]
To solve key visual image repeat, I modify the index.css:
1. html, body set as (1) width: 100%;  (2) overflow-x: hidden;
2. banner image set as background size: cover;

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
