### PR TITLE
update app.py with part1 assignment; add data folder to .gitignore

### PR DESCRIPTION
**Pull request by esperanzacheng**
http://54.87.33.165:3000/api/attractions?page=4
http://54.87.33.165:3000/api/attractions?page=0&keyword=北
http://54.87.33.165:3000/api/attraction/1
http://54.87.33.165:3000/api/categories

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Some issues:

1. `images` field of attraction should be a string array where every image URL of attraction should be a element in this array. For example: `["Image URL 1", "Image URL 2", ...]`
2. `null` is not `"null"`
3. Use keyword to filter category and name, not description.

Fix issues and re-request review.

**Comment by esperanzacheng** [comment]
fix the issue mentioned before. Thanks!

http://54.87.33.165:3000/api/attractions?page=4
[http://54.87.33.165:3000/api/attractions?page=0&keyword=北](http://54.87.33.165:3000/api/attractions?page=0&keyword=%E5%8C%97)
http://54.87.33.165:3000/api/attraction/1
http://54.87.33.165:3000/api/categories

**Review by cwpeng — CHANGES_REQUESTED** [review]
Result is OK. But you don't need to do validate query like below:
```
		validate_query = "SELECT id FROM Attraction"
		my_cursor.execute(validate_query)
```
It's too expensive to get all data just for validation.

It's easy to know if there exists data with specific id after execute query.

**Comment by esperanzacheng** [comment]
delete redundant validation code
change validation method with try/except (ValueError, IndexError, TypeError)

**Review by cwpeng — APPROVED** [review]
OK. Done. But who are you?

**Comment by esperanzacheng** [comment]
鄭晴云 (Discord: Erin Cheng)

**Pull request merged**
